/*
 * SPDX-FileCopyrightText: Copyright 2024-2026 NXP
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_THEAD_TH1520_INTC_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_THEAD_TH1520_INTC_H_

#define IRQ_TYPE_NONE           0
#define IRQ_TYPE_EDGE_RISING    1
#define IRQ_TYPE_EDGE_FALLING   2
#define IRQ_TYPE_EDGE_BOTH      (IRQ_TYPE_EDGE_FALLING | IRQ_TYPE_EDGE_RISING)
#define IRQ_TYPE_LEVEL_HIGH     4
#define IRQ_TYPE_LEVEL_LOW      8

/* IRQ numbers
 * > 0-15 interrupts of C910 are reserved for internal use, so the 
 * > actual interrupt number is the interrupt number plus 16.
 */
#define INTR_SOURCE_OFFSET      (16)
#define TIMER0_0_INTR_SOURCE    (0  + INTR_SOURCE_OFFSET)
#define TIMER0_1_INTR_SOURCE    (1  + INTR_SOURCE_OFFSET)
#define TIMER0_2_INTR_SOURCE    (2  + INTR_SOURCE_OFFSET)
#define TIMER0_3_INTR_SOURCE    (3  + INTR_SOURCE_OFFSET)
#define TIMER1_0_INTR_SOURCE    (4  + INTR_SOURCE_OFFSET)
#define TIMER1_1_INTR_SOURCE    (5  + INTR_SOURCE_OFFSET)
#define TIMER1_2_INTR_SOURCE    (6  + INTR_SOURCE_OFFSET)
#define TIMER1_3_INTR_SOURCE    (7  + INTR_SOURCE_OFFSET)
#define WDT0_INTR_SOURCE        (8  + INTR_SOURCE_OFFSET)
#define WDT1_INTR_SOURCE        (9  + INTR_SOURCE_OFFSET)
#define BMU_C910_INTR_SOURCE    (10 + INTR_SOURCE_OFFSET)
#define DMAC_CPUSYS_INTR_SOURCE (11 + INTR_SOURCE_OFFSET)
#define MBOX0_INTR_SOURCE       (12 + INTR_SOURCE_OFFSET)
#define MBOX1_INTR_SOURCE       (13 + INTR_SOURCE_OFFSET)
#define MBOX2_INTR_SOURCE       (14 + INTR_SOURCE_OFFSET)
#define MBOX3_INTR_SOURCE       (15 + INTR_SOURCE_OFFSET)
// 16-19 reserved
#define UART0_INTR_SOURCE       (20 + INTR_SOURCE_OFFSET)
#define UART1_INTR_SOURCE       (21 + INTR_SOURCE_OFFSET)
#define UART2_INTR_SOURCE       (22 + INTR_SOURCE_OFFSET)
#define UART3_INTR_SOURCE       (23 + INTR_SOURCE_OFFSET)
#define UART4_INTR_SOURCE       (24 + INTR_SOURCE_OFFSET)
#define UART5_INTR_SOURCE       (25 + INTR_SOURCE_OFFSET)
// 26-27 reserved
#define IC20_INTR_SOURCE        (28 + INTR_SOURCE_OFFSET)
#define IC21_INTR_SOURCE        (29 + INTR_SOURCE_OFFSET)
#define IC22_INTR_SOURCE        (30 + INTR_SOURCE_OFFSET)
#define IC23_INTR_SOURCE        (31 + INTR_SOURCE_OFFSET)
#define IC24_INTR_SOURCE        (32 + INTR_SOURCE_OFFSET)
#define IC25_INTR_SOURCE        (33 + INTR_SOURCE_OFFSET)
// 34-35 reserved
#define QSPI0_INTR_SOURCE       (36 + INTR_SOURCE_OFFSET)
#define QSPI1_INTR_SOURCE       (37 + INTR_SOURCE_OFFSET)
#define SPI_INTR_SOURCE         (38 + INTR_SOURCE_OFFSET)
#define GPIO4_INTR_SOURCE       (39 + INTR_SOURCE_OFFSET)
#define GPIO0_INTR_SOURCE       (40 + INTR_SOURCE_OFFSET)
#define GPIO1_INTR_SOURCE       (41 + INTR_SOURCE_OFFSET)
#define GPIO2_INTR_SOURCE       (42 + INTR_SOURCE_OFFSET)
#define GPIO3_INTR_SOURCE       (43 + INTR_SOURCE_OFFSET)
#define PWM_INTR_SOURCE         (44 + INTR_SOURCE_OFFSET)
#define ADC_INTR_SOURCE         (45 + INTR_SOURCE_OFFSET)

// 46-207 : TODO: other interrupt sources

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_THEAD_TH1520_INTC_H_ */
